name: Validate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - uses: "actions/checkout@v4"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"